// Generated by CoffeeScript 1.10.0
(function() {
  var client, diceroll, discord, token;

  discord = require('discord.js');

  client = new discord.Client();

  token = process.env.DISCORD_KEY;

  diceroll = require('./diceroll');

  client.on('ready', function() {
    return console.log('login!');
  });

  client.on('message', function(message) {
    var m, msg, roll;
    if (message.author.bot) {

    } else {
      if (m = message.content.match(/(\d+)[dD](\d+)(.*)/)) {
        roll = diceroll.roll(m[1], m[2]);
        msg = "[" + roll.join(",") + "]: -> " + diceroll.sum(roll);
        if (m[3].match(/シークレット/)) {
          message.author.send(msg);
        } else {
          return message.reply(msg);
        }
      }
    }
  });

  client.login(token);

}).call(this);
