// Generated by CoffeeScript 1.10.0
var diceroll, sumList;

diceroll = function(res, n, m) {
  var dice;
  if (n <= 0) {
    return res;
  } else {
    dice = Math.floor(Math.random() * m + 1);
    res.push(dice);
    return diceroll(res, n - 1, m);
  }
};

exports.roll = function(n, m) {
  return diceroll([], n, m);
};

sumList = function(arr) {
  var t;
  if (arr.length === 0) {
    return 0;
  } else {
    t = arr.shift();
    return t + sumList(arr);
  }
};

exports.sum = function(arr) {
  return sumList(arr);
};
